### ISSUE TITLE
Error: Cannot read properties of undefined (reading 'body')

### ISSUE THREAD

**Issue by cjshrader** [nhevia/discord-styled-releases#12]
Hey, this is my first time setting something like this up so it's possible I did something wrong but this is the error I am getting.

In my release.yml, I added this as one of the steps:

```yaml
      - name: Sending message to Discord with release notes
        uses: nhevia/discord-styled-releases@main
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
```

I added the appropriate secrets to our project, under Actions.

When the action runs, I see the following:

```
Run nhevia/discord-styled-releases@main
  with:
    webhook_id: ***
    webhook_token: ***
  env:
    pythonLocation: C:\hostedtoolcache\windows\Python\3.13.1\x64
    PKG_CONFIG_PATH: C:\hostedtoolcache\windows\Python\3.13.1\x64/lib/pkgconfig
    Python_ROOT_DIR: C:\hostedtoolcache\windows\Python\3.13.1\x64
    Python[2](https://github.com/d4lfteam/d4lf/actions/runs/13228738007/job/36922949699#step:9:2)_ROOT_DIR: C:\hostedtoolcache\windows\Python\[3](https://github.com/d4lfteam/d4lf/actions/runs/13228738007/job/36922949699#step:9:3).13.1\x64
    Python3_ROOT_DIR: C:\hostedtoolcache\windows\Python\3.13.1\x6[4](https://github.com/d4lfteam/d4lf/actions/runs/13228738007/job/36922949699#step:9:4)
    VERSION: 6.0.0alpha10
    IS_BETA: true
Error: Cannot read properties of undefined (reading 'body')
```

Any suggestions?
